version: "3.9"

services:
  db:
    image: postgres:15
    container_name: voicenudge-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voicenudge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: voicenudge-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
