"""Text and Due at added to hitory table

Revision ID: 332ffb34f67a
Revises: caae6ab29abd
Create Date: 2025-09-17 20:03:47.692798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332ffb34f67a'
down_revision = 'caae6ab29abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_column('due_at')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
